from sqlmodel import Session

from ..models.compliance_review import ComplianceReview
from ..schemas.compliance_review import ComplianceReviewCreate
from .workflow_utils import encode_json, extract_source_document_ids, touch


def create_compliance_review(
    db: Session,
    *,
    bank_id: int,
    created_by: int,
    data: ComplianceReviewCreate,
) -> ComplianceReview:
    record = ComplianceReview(
        bank_id=bank_id,
        created_by=created_by,
        assigned_to=data.assigned_to,
        title=data.title,
        circular_document_id=data.circular_document_id,
        affected_departments_json=encode_json(data.affected_departments),
        approval_status="requires_officer_review",
    )
    db.add(record)
    db.commit()
    db.refresh(record)
    return record


def update_compliance_review_summary(
    db: Session,
    *,
    review_id: int,
    generated_by: int,
    impact_summary: str,
    obligations: list[dict] | None = None,
    sources: list[dict] | None = None,
) -> ComplianceReview:
    record = db.get(ComplianceReview, review_id)
    if record is None:
        raise ValueError("Compliance review not found")

    record.impact_summary = impact_summary
    record.obligations_json = encode_json(obligations or [])
    record.source_document_ids_json = encode_json(extract_source_document_ids(sources))
    record.status = "under_review"
    record.approval_status = "requires_officer_review"
    record.reviewer_notes = record.reviewer_notes or f"AI draft generated by user {generated_by}; officer review required."
    touch(record)
    db.add(record)
    db.commit()
    db.refresh(record)
    return record
